bot_token: "<your_bot_token>"

webhook:
  enabled: false
  listen_ip: "127.0.0.1"
  listen_port: 9001
  listen_path: "/"
  url: "example.com/test"
  cert_path: ""
  cert_key_path: ""

prometheus:
  enabled: false
  listen: 127.0.0.1:9101
  export_port: 9090
